### ISSUE TITLE
PyHEP 2024 "proceedings" - tag/release for Zenodo

### ISSUE THREAD

**Issue by eduardo-rodrigues** [MatteoRobbiati/Qibo-PyHEP#1]
This refers to https://indico.cern.ch/event/1384010/page/32779-proceedings:

Hello, could you prepare a tag/release of this repo you used for your PyHEP 2024 presentation so that I then mint a DOI on Zenodo, to be citable? Talks are trivial but for repositories a tag is a requirement for the minting.

You can see last year's example at https://zenodo.org/communities/pyhep2023/.

Let me know when done and I will take care of the rest. Advance thanks.

**Comment by MatteoRobbiati** [comment]
Hi there! I just created a tag [here](https://github.com/MatteoRobbiati/Qibo-PyHEP/tags). 
The official package is [Qibo](https://github.com/qiboteam/qibo), but I think here we want to refer to the talk material, right?

**Comment by eduardo-rodrigues** [comment]
Hi. Yes, I do mean the talk material, hence this repo :). Many thanks.

**Comment by MatteoRobbiati** [comment]
> Hi. Yes, I do mean the talk material, hence this repo :). Many thanks.

Thanks :)
